customization:
  distribution_code_name: Weasel
  distribution_version: 0.14.3_dev_0.8
  generator: "Rime::SwitcherSettings"
  modified_time: "Sun Mar 26 20:38:02 2023"
  rime_version: 1.8.5
patch:
  schema_list:
    - {schema: wubi98_ci}
    - {schema: wubi98_dz}