distribution_code_name: Weasel
distribution_name: "小狼毫"
distribution_version: 0.16.3
install_time: "Sun Nov  3 14:58:23 2024"
installation_id: "5f68f8f7-1a34-44fe-b7a5-52e0b80508a4"
rime_version: 1.11.2