# Squirrel settings
# encoding: utf-8
# by: 空山明月
# date: 2024-05-27

config_version: '0.38'
keyboard_layout: last
chord_duration: 0.1  # seconds
show_notifications_when: appropriate

style:
  color_scheme: poetry_ocean
  color_scheme_dark: dark_ocean
  text_orientation: horizontal  # horizontal | vertical
  inline_preedit: true
  corner_radius: 10
  hilited_corner_radius: 0
  border_height: 0
  border_width: 0
  # space between candidates in stacked layout
  line_spacing: 5
  # space between preedit and candidates in non-inline mode
  spacing: 10
  candidate_format: '%c %@'
  # adjust the base line of vertical text
  #base_offset: 6
  font_face: 'Lucida Grande'
  font_point: 21
  label_font_face: 'Lucida Grande'
  label_font_point: 18
  comment_font_face: 'Lucida Grande, 雅黑字根, 黑体字根'
  comment_font_point: 18

preset_color_schemes:
  native:
    name: 系統配色

  poetry_ocean:
    name: 诗意之海／Poetry Ocean
    author: 空山明月 <mrshiqiqi@126.com>
    text_color: 0x333333
    back_color: 0xFEE6D3
    label_color: 0x333333
    candidate_text_color: 0x333333
    hilited_text_color: 0x333333
    hilited_candidate_label_color: 0xFFFFFF
    hilited_candidate_text_color: 0xFFFFFF
    hilited_candidate_back_color: 0xB5513F
    comment_text_color: 0x333333
    hilited_comment_text_color: 0xFFFFFF

  dark_ocean:
    name: 深海无垠／Dark Ocean
    author: 空山明月 <mrshiqiqi@126.com>
    text_color: 0xFFFFFF
    back_color: 0x4b4848
    label_color: 0xe0e0e0
    candidate_text_color: 0xFFFFFF
    hilited_text_color: 0xFFFFFF
    hilited_candidate_label_color: 0xe0e0e0
    hilited_candidate_text_color: 0xFFFFFF
    hilited_candidate_back_color: 0xB5513F
    comment_text_color: 0xe0e0e0
    hilited_comment_text_color: 0xe0e0e0

app_options:
  com.apple.Spotlight:
    ascii_mode: true
  com.alfredapp.Alfred:
    ascii_mode: true
  com.runningwithcrayons.Alfred-2:
    ascii_mode: true
  com.blacktree.Quicksilver:
    ascii_mode: true
  com.apple.Terminal:
    ascii_mode: true
    no_inline: true
  com.googlecode.iterm2:
    ascii_mode: true
    no_inline: true
  org.vim.MacVim:
    ascii_mode: true  # 初始爲西文模式
    no_inline: true   # 不使用行內編輯
    vim_mode: true    # 退出VIM插入模式自動切換輸入法狀態
  com.apple.dt.Xcode:
    ascii_mode: true
  com.barebones.textwrangler:
    ascii_mode: true
  com.macromates.TextMate.preview:
    ascii_mode: true
  com.github.atom:
    ascii_mode: true
  com.microsoft.VSCode:
    ascii_mode: true
  com.sublimetext.2:
    ascii_mode: true
  org.gnu.Aquamacs:
    ascii_mode: true
  org.gnu.Emacs:
    ascii_mode: true
    no_inline: true
  co.zeit.hyper:
    ascii_mode: true
  com.google.Chrome:
    # 規避 https://github.com/rime/squirrel/issues/435
    inline: true
  ru.keepcoder.Telegram:
    # 規避 https://github.com/rime/squirrel/issues/475
    inline: true