# Weasel settings
# encoding: utf-8
# by: 空山明月
# date: 2024-05-27

config_version: "0.26"

### 样式
style:
  # ...外观...
  color_scheme: poetry_ocean                      # 日间主题
  color_scheme_dark: dark_ocean                   # 夜间主题
  # ...字体...
  font_face: 霞鹜新致宋 屏幕阅读版                      # 全局字体
  label_font_face: 霞鹜新致宋 屏幕阅读版                # 标签字体
  comment_font_face: 黑体字根                      # 注释字体
  font_point: 13                                  # 全局字号
  label_font_point: 13                            # 标签字号
  comment_font_point: 13                          # 注释字号
  # ... 窗口...
  fullscreen: false                               # 是否全屏模式
  horizontal: false                               # 是否横向布局
  vertical_text: true                             # 是否启用竖排文本
  vertical_text_left_to_right: true               # 竖排方向是否从左到右
  vertical_text_with_wrap: false                  # 文本竖排模式下是否自动换行
  vertical_auto_reverse: false                    # 文本竖排模式下，候选窗口位于光标上方时倒序排序
  # ...预编辑区...
  inline_preedit: true                            # 是否在行内显示预编辑区
  preedit_type: composition                       # 预编辑区显示内容 composition（编码）；preview（高亮候选）；preview_all（全部候选）
  # ...其他选项...
  label_format: "%s"                              # 标签字符号
  mark_text: ""                                   # 候选项前的标记符号
  ascii_tip_follow_cursor: false                  # 切换 ASCII 模式时，提示跟随鼠标，而非输入光标
  enhanced_position: false                        # 无法定位候选框时，在窗口左上角显示候选框
  display_tray_icon: false                        # 托盘显示独立于语言栏的额外图标
  antialias_mode: default                         # antialias_mode (default；force_dword；cleartype；grayscale；aliased)
  candidate_abbreviate_length: 20                 # 候选项略写，超过此数字则用省略号代替。设置为 0 则不启用此功能
  paging_on_scroll: false                         # 在候选窗口上滑动滚轮的行为：true（翻页）；false（选中下一个候选）
  click_to_capture: true                          # 鼠标点击候选项，创建截图
  ### 布局
  layout:
    align_type: center                            # 标签、候选文字、注解文字之间的相对对齐方式 (top ; center ; bottom)
    max_height: 0                                 # 候选框最大高度，0 不启用此功能
    max_width: 0                                  # 候选框最大宽度，0 不启用此功能
    min_height: 0                                 # 候选框最小高度
    min_width: 0                                  # 候选框最小宽度
    border_width: 0                               # 边框宽度
    margin_x: 0                                   # 主体元素和候选框的左右、上下边距，为负值时，不显示候选框
    margin_y: 0                                   # 主体元素和候选框的左右、上下边距，为负值时，不显示候选框
    spacing: 5                                    # inline_preedit 为 false 时，编码区域和候选区域的间距
    candidate_spacing: 8                          # 候选项之间的间距
    hilite_spacing: 8                             # 候选项和相应标签的间距，候选项与注解文字之间的距离
    hilite_padding: 8                             # 高亮区域和内部文字的间距，影响高亮区域大小
    shadow_radius: 8                              # 阴影区域半径，为 0 不显示阴影；需要同时在配色方案中指定非透明的阴影颜色
    shadow_offset_x: 2                            # 阴影绘制的偏离距离
    shadow_offset_y: 2                            # 阴影绘制的偏离距离
    corner_radius: 13                             # 候选窗口圆角半径
    round_corner: 13                              # 候选背景色块圆角半径，别名 hilited_corner_radius

preset_color_schemes:
  poetry_ocean:                                          
    name: 诗意之海／Poetry Ocean      
    author: 空山明月<mrshiqiqi@126.com>
    text_color: 0x333333                          # 默认文字颜色
    comment_text_color: 0x333333                  # 注释文字颜色
    label_color: 0x333333                         # 标签文字颜色
    back_color: 0xFEE6D3                          # 候选窗背景色
    shadow_color: 0x66000000                      # 候选窗阴影色
    border_color: 0xFFFFFF                        # 候选窗边框颜色
    hilited_text_color: 0x333333                  # 编码文字颜色
    hilited_back_color: 0xd4d4d4                  # 编码背景颜色
    # hilited_shadow_color: 0x00000000            # 编码背景块阴影颜色
    hilited_candidate_text_color: 0xFFFFFF        # 高亮候选文字颜色
    hilited_candidate_back_color: 0xB5513F        # 高亮候选背景颜色
    hilited_label_color: 0xFFFFFF                 # 高亮候选的标签颜色
    # hilited_mark_color: 0xFFFFFF                # 高亮候选前的标记颜色
    hilited_comment_text_color: 0xFFFFFF          # 高亮候选的注释颜色
    candidate_text_color: 0x000000                # 非高亮候选文字颜色
    candidate_back_color: 0xFEE6D3                # 非高亮候选背景颜色
    # candidate_shadow_color: 0x00000000          # 非高亮候选背景块阴影颜色

  dark_ocean:                                          
    name: 深海无垠／Dark Ocean      
    author: 空山明月<mrshiqiqi@126.com>
    text_color: 0xFFFFFF                          # 默认文字颜色
    comment_text_color: 0xe0e0e0                  # 注释文字颜色
    label_color: 0xe0e0e0                         # 标签文字颜色
    back_color: 0x4b4848                          # 候选窗背景色
    shadow_color: 0x66000000                      # 候选窗阴影色
    border_color: 0x4b4848                        # 候选窗边框颜色
    hilited_text_color: 0xFFFFFF                  # 编码文字颜色
    hilited_back_color: 0xd4d4d4                  # 编码背景颜色
    # hilited_shadow_color: 0x00000000            # 编码背景块阴影颜色
    hilited_candidate_text_color: 0xFFFFFF        # 高亮候选文字颜色
    hilited_candidate_back_color: 0xB5513F        # 高亮候选背景颜色
    hilited_label_color: 0xe0e0e0                 # 高亮候选的标签颜色
    # hilited_mark_color: 0xFFFFFF                # 高亮候选前的标记颜色
    hilited_comment_text_color: 0xe0e0e0          # 高亮候选的注释颜色
    candidate_text_color: 0xFFFFFF                # 非高亮候选文字颜色
    candidate_back_color: 0x4b4848                # 非高亮候选背景颜色
    # candidate_shadow_color: 0x00000000          # 非高亮候选背景块阴影颜色